#ifndef LCMAKE_TEST_INCLUDE_04_STATIC_LIBRARY_HELLO_H_
#define LCMAKE_TEST_INCLUDE_04_STATIC_LIBRARY_HELLO_H_

class Hello {
 public:
  void Print();
};

#endif // LCMAKE_TEST_INCLUDE_04_STATIC_LIBRARY_HELLO_H_